pipeline:
  build:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile
      - yarn build:ci
  test:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile
      - yarn build:ci